name: publish-blog


on:
  push:
    branches: main
    paths: blog/*.ipynb


jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout notebooks repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: blog/
        fetch-depth: 2  # Required for accessing HEAD~1.

    # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md
    - name: Generate GitHub Apps token for blog repo
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_KEY }}
        owner: ${{ github.repository_owner }}
        repositories: blog

    - name: Checkout blog repo using GitHub Apps token
      uses: actions/checkout@v4
      with:
        repository: "${{ github.repository_owner }}/blog"
        token: ${{ steps.app-token.outputs.token }}
        path: blog-repo/
        sparse-checkout: docs/posts/
        fetch-depth: 1

    # https://docs.astral.sh/uv/guides/integration/github/#caching
    - name: Install uv with cache enabled
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Converted edited notebook to Markdown and push to blog repo
      run: |
        edited=$(git diff --name-only HEAD HEAD~1 | head -n 1)
        if [ -f "$edited" ]; then
          uvx --from nbconvert jupyter nbconvert --to markdown "$edited"
        else
          echo "$edited is not a regular file."
          exit 1
        fi

        edited=${edited%.*}  # Remove extension.
        cp -t blog-repo/docs/posts/ "${edited}.md"

        edited=${edited##*/}  # Also remove parent directory.
        cd blog-repo/
        git config set user.name "github-actions[bot]"
        git config set user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/posts/
        git commit -m "feat: Update \`${edited}.md\`"
        git push
